# Generated by Django 5.2.8 on 2025-11-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('student', 'Student')], max_length=15),
        ),
    ]
