# Generated by Django 5.2.8 on 2025-12-15 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='registration_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='term',
            name='registration_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
