# Generated by Django 5.2.8 on 2025-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_term_is_active_term_registration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='max_units',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='term',
            name='min_units',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
