# Generated by Django 5.2.8 on 2025-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_term_max_units_term_min_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('ready', 'Ready'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='planning', max_length=16),
        ),
    ]
