# Generated by Django 5.1.6 on 2025-12-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='offerings.section'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_old', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('section', 'prerequisite_course')},
        ),
    ]
