# Generated by Django 5.1.6 on 2025-12-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0002_alter_prerequisite_unique_together_and_more'),
    ]

    operations = [
        # Populate course from section.course for existing prerequisites using raw SQL
        migrations.RunSQL(
            sql="""
                UPDATE offerings_prerequisite 
                SET course_id = (
                    SELECT course_id 
                    FROM offerings_section 
                    WHERE offerings_section.id = offerings_prerequisite.section_id
                )
                WHERE section_id IS NOT NULL;
                
                DELETE FROM offerings_prerequisite 
                WHERE section_id IS NOT NULL 
                AND course_id IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
