# Generated by Django 5.2.8 on 2025-12-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_classroom_examhall'),
        ('offerings', '0002_section_schedule_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionexam',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_exams', to='departments.classroom'),
        ),
        migrations.AddField(
            model_name='sectionexam',
            name='exam_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_exams', to='departments.examhall'),
        ),
        migrations.AddField(
            model_name='sectionschedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_schedules', to='departments.classroom'),
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
