# Generated by Django 5.1.6 on 2025-12-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0003_migrate_prerequisite_data'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle the model state mismatch
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Remove section field from database
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE new_offerings_prerequisite (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            course_id INTEGER NOT NULL REFERENCES courses_course(id),
                            prerequisite_course_id INTEGER NOT NULL REFERENCES courses_course(id),
                            UNIQUE(course_id, prerequisite_course_id)
                        );
                        INSERT INTO new_offerings_prerequisite (id, course_id, prerequisite_course_id)
                        SELECT id, course_id, prerequisite_course_id FROM offerings_prerequisite;
                        DROP TABLE offerings_prerequisite;
                        ALTER TABLE new_offerings_prerequisite RENAME TO offerings_prerequisite;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                # Remove section field from model state
                migrations.RemoveField(
                    model_name='prerequisite',
                    name='section',
                ),
                # Make course non-nullable in model state
                migrations.AlterField(
                    model_name='prerequisite',
                    name='course',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prerequisites',
                        to='courses.course'
                    ),
                ),
                # Update unique_together in model state
                migrations.AlterUniqueTogether(
                    name='prerequisite',
                    unique_together={('course', 'prerequisite_course')},
                ),
            ],
        ),
    ]
